-- Migration: invoice-lifecycle (fakturačný systém krok 13c – automatizácia + životný cyklus)
-- Aditívne: nové enum hodnoty + nové stĺpce (žiadny existujúci stĺpec sa nemení).

-- InvoiceStatus: pridať SENT, PAID (PG12+ idempotentný IF NOT EXISTS; nové hodnoty sa v tejto migrácii nepoužívajú).
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'SENT';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'PAID';

-- Invoice: životný cyklus + auto-generovanie
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "sentAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "paidOutAt" TIMESTAMP(3);

-- Organizer: jazyk fakturačných e-mailov
ALTER TABLE "Organizer" ADD COLUMN IF NOT EXISTS "locale" TEXT NOT NULL DEFAULT 'sk';
