import { apiFetch, API_BASE } from '@/lib/api';
import { BillingMode } from '@/lib/api/organizers-admin';

export type InvoiceStatus = 'DRAFT' | 'FINALIZED' | 'SENT' | 'PAID';
export type InvoiceLineType = 'COMMISSION' | 'REFUND_FEE' | 'CUSTOM';

export interface InvoiceLine {
  id: string;
  type: InvoiceLineType;
  description: string;
  quantity: number;
  unitPriceCents: number;
  vatPercent: number;
  lineNetCents: number;
  lineVatCents: number;
  lineTotalCents: number;
  sortOrder: number;
}

export interface Invoice {
  id: string;
  organizerId: string;
  status: InvoiceStatus;
  invoiceNumber: string | null;
  billingMode: BillingMode;
  terminId: string | null;
  periodFrom: string | null;
  periodTo: string | null;
  issueDate: string;
  taxDate: string;
  dueDate: string;
  currency: string;
  buyerName: string | null;
  buyerCompany: string | null;
  buyerIco: string | null;
  buyerDic: string | null;
  buyerIcDph: string | null;
  buyerAddress: string | null;
  buyerIban: string | null;
  subtotalCents: number;
  vatTotalCents: number;
  totalCents: number;
  snapTicketsSold: number;
  snapRevenueCents: number;
  snapRefundedTickets: number;
  snapNetPayoutCents: number;
  note: string | null;
  createdAt: string;
  autoGenerated: boolean;
  sentAt: string | null;
  paidAt: string | null;
  paidOutAt: string | null;
  lineItems: InvoiceLine[];
  organizer?: { name: string };
}

export interface InvoiceListRow extends Omit<Invoice, 'lineItems'> {
  organizer: { name: string };
}

export interface BillingOrganizerRow {
  organizerId: string;
  name: string;
  companyName: string | null;
  billingMode: BillingMode;
  revenueCents: number;
  netPayoutCents: number;
}

export interface BillingStatement {
  ticketsSold: number;
  revenueCents: number;
  commissionPercent: number;
  commissionCents: number;
  vatPercent: number;
  vatCents: number;
  refundedTickets: number;
  refundFeePerTicketCents: number;
  refundFeesCents: number;
  netPayoutCents: number;
  customerFeesCents: number;
}

export interface BillingPastTermin {
  id: string;
  startsAt: string;
  endsAt: string | null;
  showName: string | null;
}

/** SUPERADMIN/STAFF – read-only fakturačný prehľad. */
export const billingApi = {
  organizers: (token: string) =>
    apiFetch<BillingOrganizerRow[]>('/v1/admin/billing/organizers', { token }),

  pastTermins: (id: string, token: string) =>
    apiFetch<BillingPastTermin[]>(`/v1/admin/billing/organizers/${id}/past-termins`, { token }),

  statementByTermin: (id: string, occurrenceId: string, token: string) =>
    apiFetch<BillingStatement>(`/v1/admin/billing/organizers/${id}/statement?occurrenceId=${occurrenceId}`, { token }),

  statementByRange: (id: string, from: string, to: string, token: string) =>
    apiFetch<BillingStatement>(`/v1/admin/billing/organizers/${id}/statement?from=${from}&to=${to}`, { token }),

  // ── Faktúry (krok 13b) ──
  createInvoice: (orgId: string, body: { occurrenceId?: string; from?: string; to?: string }, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/organizers/${orgId}/invoices`, { method: 'POST', body: JSON.stringify(body), token }),

  listInvoices: (token: string, params: { organizerId?: string; status?: InvoiceStatus } = {}) => {
    const qp = new URLSearchParams();
    if (params.organizerId) qp.set('organizerId', params.organizerId);
    if (params.status) qp.set('status', params.status);
    const s = qp.toString();
    return apiFetch<InvoiceListRow[]>(`/v1/admin/billing/invoices${s ? `?${s}` : ''}`, { token });
  },

  getInvoice: (id: string, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}`, { token }),

  addLineItem: (id: string, body: { description: string; quantity: number; unitPriceCents: number; vatPercent: number }, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}/line-items`, { method: 'POST', body: JSON.stringify(body), token }),

  updateLineItem: (id: string, lineId: string, body: Partial<{ description: string; quantity: number; unitPriceCents: number; vatPercent: number }>, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}/line-items/${lineId}`, { method: 'PATCH', body: JSON.stringify(body), token }),

  deleteLineItem: (id: string, lineId: string, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}/line-items/${lineId}`, { method: 'DELETE', token }),

  updateInvoice: (id: string, body: { taxDate?: string; dueDate?: string; note?: string }, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}`, { method: 'PATCH', body: JSON.stringify(body), token }),

  finalize: (id: string, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}/finalize`, { method: 'POST', token }),

  sendInvoice: (id: string, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}/send`, { method: 'POST', token }),

  markPaid: (id: string, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}/mark-paid`, { method: 'POST', token }),

  markPaidOut: (id: string, token: string) =>
    apiFetch<Invoice>(`/v1/admin/billing/invoices/${id}/mark-paid-out`, { method: 'POST', token }),

  runAutoGeneration: (mode: 'per_event' | 'monthly' | 'all', token: string) =>
    apiFetch<{ mode: string; created: number }>(`/v1/admin/billing/run-auto-generation?mode=${mode}`, { method: 'POST', token }),

  deleteInvoice: (id: string, token: string) =>
    apiFetch<{ deleted: boolean }>(`/v1/admin/billing/invoices/${id}`, { method: 'DELETE', token }),

  invoicePdf: async (id: string, token: string): Promise<Blob> => {
    const res = await fetch(`${API_BASE}/v1/admin/billing/invoices/${id}/pdf`, { headers: { Authorization: `Bearer ${token}` } });
    if (!res.ok) throw new Error(`PDF ${res.status}`);
    return res.blob();
  },
};
