import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { BillingService } from './billing.service';
import { InvoiceService } from './invoice.service';

const TZ = 'Europe/Bratislava';

export type AutoGenMode = 'per_event' | 'monthly' | 'all';

/**
 * Krok 13c: scheduled auto-generovanie DRAFT faktúr.
 * - PER_EVENT: každú hodinu – odohrané/zrušené termíny bez faktúry.
 * - MONTHLY: denne o 03:00 – predchádzajúci kalendárny mesiac (agregát), idempotentne.
 * Cron AUTO-generuje LEN DRAFTY. Finalizácia + odoslanie sú manuálne (super admin),
 * pokiaľ nie je zapnutý ENV flag BILLING_AUTO_SEND (default false).
 * Beží len v 1 inštancii (1 backend kontajner).
 */
@Injectable()
export class BillingSchedulerService {
  private readonly logger = new Logger(BillingSchedulerService.name);

  constructor(
    private prisma: PrismaService,
    private billing: BillingService,
    private invoices: InvoiceService,
    private config: ConfigService,
  ) {}

  private get autoSend(): boolean {
    return this.config.get<string>('BILLING_AUTO_SEND', 'false') === 'true';
  }

  @Cron('0 * * * *', { timeZone: TZ })
  async cronPerEvent() {
    const n = await this.runPerEvent();
    if (n > 0) this.logger.log(`[cron per_event] vytvorených draftov: ${n}`);
  }

  @Cron('0 3 * * *', { timeZone: TZ })
  async cronMonthly() {
    const n = await this.runMonthly();
    if (n > 0) this.logger.log(`[cron monthly] vytvorených draftov: ${n}`);
  }

  /** Manuálny / cron spúšťač – vráti počet vytvorených draftov. */
  async runAuto(mode: AutoGenMode): Promise<{ mode: AutoGenMode; created: number }> {
    let created = 0;
    if (mode === 'per_event' || mode === 'all') created += await this.runPerEvent();
    if (mode === 'monthly' || mode === 'all') created += await this.runMonthly();
    return { mode, created };
  }

  // ─────────────────────── PER_EVENT ───────────────────────
  private async runPerEvent(): Promise<number> {
    const now = new Date();
    // Kandidáti: termíny PER_EVENT organizátorov, ktoré sú odohrané (endsAt<now,
    // fallback startsAt<now) ALEBO zrušené.
    const termins = await this.prisma.termin.findMany({
      where: {
        show: { organizer: { billingMode: 'PER_EVENT' } },
        OR: [
          { endsAt: { lt: now } },
          { endsAt: null, startsAt: { lt: now } },
          { status: 'CANCELLED' },
        ],
      },
      select: { id: true, show: { select: { organizerId: true } } },
    });
    if (!termins.length) return 0;

    // Vylúč termíny ktoré UŽ majú faktúru (idempotencia).
    const existing = await this.prisma.invoice.findMany({
      where: { terminId: { in: termins.map((t) => t.id) } },
      select: { terminId: true },
    });
    const invoiced = new Set(existing.map((e) => e.terminId));

    let created = 0;
    for (const t of termins) {
      if (invoiced.has(t.id)) continue;
      try {
        const st = await this.billing.computeStatement(t.show.organizerId, { occurrenceId: t.id });
        if (st.commissionCents <= 0 && st.refundFeesCents <= 0) continue; // nič na fakturáciu
        const inv = await this.invoices.createDraft(t.show.organizerId, { occurrenceId: t.id }, undefined, { autoGenerated: true });
        created++;
        await this.maybeAutoSend(inv.id);
      } catch (e) {
        this.logger.error(`per_event termin ${t.id}: ${(e as Error).message}`);
      }
    }
    return created;
  }

  // ─────────────────────── MONTHLY ───────────────────────
  /** Hranice predchádzajúceho kalendárneho mesiaca v Europe/Bratislava (UTC Date). */
  private prevMonthRange(): { from: Date; to: Date } {
    const now = new Date();
    const parts = new Intl.DateTimeFormat('en-CA', { timeZone: TZ, year: 'numeric', month: 'numeric' }).formatToParts(now);
    let y = Number(parts.find((p) => p.type === 'year')!.value);
    let mo = Number(parts.find((p) => p.type === 'month')!.value); // 1-12
    mo -= 1;
    if (mo === 0) { mo = 12; y -= 1; }
    const from = new Date(Date.UTC(y, mo - 1, 1, 0, 0, 0));
    const to = new Date(Date.UTC(y, mo, 0, 23, 59, 59));
    return { from, to };
  }

  private async runMonthly(): Promise<number> {
    const { from, to } = this.prevMonthRange();
    const orgs = await this.prisma.organizer.findMany({
      where: { billingMode: 'MONTHLY' },
      select: { id: true },
    });
    let created = 0;
    for (const o of orgs) {
      try {
        // Idempotencia: existuje už faktúra za toto obdobie?
        const exists = await this.prisma.invoice.findFirst({
          where: { organizerId: o.id, periodFrom: from, periodTo: to },
          select: { id: true },
        });
        if (exists) continue;
        const st = await this.billing.computeStatement(o.id, { from, to });
        if (st.commissionCents <= 0 && st.refundFeesCents <= 0) continue;
        const inv = await this.invoices.createDraft(o.id, { from, to }, undefined, { autoGenerated: true });
        created++;
        await this.maybeAutoSend(inv.id);
      } catch (e) {
        this.logger.error(`monthly organizer ${o.id}: ${(e as Error).message}`);
      }
    }
    return created;
  }

  /** ENV BILLING_AUTO_SEND=true → po vytvorení draftu aj finalizuj + odošli. Default vypnuté. */
  private async maybeAutoSend(invoiceId: string) {
    if (!this.autoSend) return;
    try {
      await this.invoices.finalize(invoiceId);
      await this.invoices.send(invoiceId);
      this.logger.log(`[auto-send] faktúra ${invoiceId} finalizovaná + odoslaná`);
    } catch (e) {
      this.logger.error(`auto-send ${invoiceId}: ${(e as Error).message}`);
    }
  }
}
