'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';
import { getValidToken } from '@/lib/auth';
import { couponsAdminApi, CreateCouponInput } from '@/lib/api/coupons';
import { Button } from '@/components/ui/button';
import { ModalShell, Field, inputCls } from './couponUi';
import { useCouponFields, FlatTicketType } from './useCouponFields';

export function CreateCouponModal({
  showId,
  ticketTypes,
  onClose,
  onCreated,
}: {
  showId: string;
  ticketTypes: FlatTicketType[];
  onClose: () => void;
  onCreated: (msg: string) => void;
}) {
  const t = useTranslations('organizer.coupon');
  const { node, buildBase } = useCouponFields({ showId, ticketTypes });
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit() {
    setError('');
    let payload: CreateCouponInput;
    try {
      payload = { ...buildBase() };
      const trimmed = code.trim().toUpperCase();
      if (trimmed) {
        if (trimmed.length < 4 || trimmed.length > 32) {
          throw new Error(t('errors.codeLength'));
        }
        payload.code = trimmed;
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : t('errors.invalid'));
      return;
    }

    setSubmitting(true);
    try {
      const token = await getValidToken();
      if (!token) throw new Error(t('errors.loginRequired'));
      const created = await couponsAdminApi.create(payload, token);
      onCreated(t('toast.created', { code: created.code }));
    } catch (e) {
      setError(e instanceof Error ? e.message : t('errors.createFailed'));
      setSubmitting(false);
    }
  }

  return (
    <ModalShell
      title={t('addCoupon')}
      onClose={onClose}
      footer={
        <>
          <Button variant="outline" onClick={onClose} disabled={submitting}>
            {t('cancel')}
          </Button>
          <Button onClick={handleSubmit} loading={submitting} disabled={submitting}>
            {t('create')}
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        <Field label={t('fields.code')} hint={t('hints.emptyAutoGenerated')}>
          <input
            value={code}
            onChange={(e) => setCode(e.target.value)}
            placeholder={t('placeholders.autoGenerated')}
            className={inputCls + ' font-mono uppercase'}
            maxLength={32}
          />
        </Field>
        {node}
        {error && <div className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}
      </div>
    </ModalShell>
  );
}
